use_frameworks!

platform :ios, '13.0'

target 'JackMa_Example' do
  pod 'JackMa', :path => '../'
  pod 'Alamofire'
  pod 'ProgressHUD'
  target 'JackMa_Tests' do
    inherit! :search_paths

    
  end
end
